---
language: node_js
node_js:
  - "node"
sudo: false
cache:
  yarn: true
dist: trusty

install: make bootstrap

jobs:
  include:
    - stage: build
      script: yarn build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: dist
        on:
          branch: master
