---
language: node_js
sudo: false
cache:
  yarn: true
dist: trusty

jobs:
  include:
    - stage: tests
      script: yarn test
    - stage: build
      script: yarn run build

branches:
  only:
  - master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
