---
language: node_js
node_js:
  - "node"
sudo: false
cache:
  yarn: true
dist: trusty

jobs:
  include:
    - stage: build
      script: yarn run build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: docs
        # target-branch: master
        on:
          branch: master

branches:
  only:
  - master
